[package]
name = "ndcell"
version = "0.1.0"
authors = ["HactarCE <6060305+HactarCE@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delegate = "0.3.0"
glium = "0.26.0-alpha3"
ndarray = "0.13.0"
regex = "1"

[dev-dependencies]
proptest = "0.9.4"
