[package]
name = "ndcell_core"
version = "0.1.0"
authors = ["HactarCE <6060305+HactarCE@users.noreply.github.com>"]
edition = "2018"

[dependencies]
dashmap = "3.4"
enum_dispatch = "0.2"
noisy_float = "0.1"
num = "0.2"
pest = "2.1"
pest_derive = "2.1"
regex = "1"
seahash = "3.0"

[dev-dependencies]
proptest = "0.9.4"
