[package]
name = "ndca"
version = "0.1.0"
authors = ["HactarCE <6060305+HactarCE@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm8-0" }
lazy_static = "1.4"
regex = "1"
thread_local = "1.0"

[dev-dependencies]
proptest = "0.9.4"
