[package]
name = "ndcell"
version = "0.0.1"
authors = ["HactarCE <6060305+HactarCE@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5"
enum_dispatch = "0.2"
glium = "0.25"
itertools = "0.9"
imgui = "0.2"
imgui-glium-renderer = "0.2"
imgui-winit-support = "0.2"
lazy_static = "1.4"
log = "0.4"
noisy_float = "0.1"
num = "0.2"
# preferences = "1.1"
send_wrapper = "0.4"
simple_logger = "1.0"

ndcell_core = { path = "../core" }
ndcell_lang = { path = "../lang" }
