[package]
name = "ndcell"
version = "0.0.1"
authors = ["HactarCE <6060305+HactarCE@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorous = "1.0"
clipboard = "0.5"
enum_dispatch = "0.3"
glium = "0.27"
itertools = "0.9"
imgui = "0.4"
imgui-glium-renderer = "0.4"
imgui-winit-support = "0.4"
lazy_static = "1.4"
log = "0.4"
parking_lot = "0.11"
# preferences = "1.1"
send_wrapper = "0.4"
simple_logger = "1.6"

ndcell_core = { path = "../core" }
ndcell_lang = { path = "../lang" }
