name: build

on:
  push:
    branches: [ stable ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  NDCELL_VERSION: 0.3.0-dev

jobs:

  windows:
    name: Build Windows latest
    runs-on: windows-latest
    env:
      LLVM_SYS_100_PREFIX: C:\LLVM
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Download LLVM
        run: git clone https://github.com/HactarCE/LLVM-MSVC-Win64-Dev C:\LLVM
      - name: Build NDCell
        run: cargo build --release
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: ndcell_v${{ env.NDCELL_VERSION }}_win64
          path: target/release/ndcell.exe

  linux:
    name: Build Linux latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
      - name: Install LLVM
        run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 10
      - name: Install ImGui dependencies
        run: sudo apt install libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Install Native File Dialog dependencies
        run: sudo apt-get install libgtk-3-dev
      - name: Build NDCell
        run: cargo build --release
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: ndcell_v${{ env.NDCELL_VERSION }}_linux
          path: target/release/ndcell

  macos:
    name: Build macOS latest
    runs-on: macos-latest
    env:
      LLVM_SYS_100_PREFIX: /tmp/LLVM
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Download LLVM
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-apple-darwin.tar.xz -O /tmp/llvm.tar.xz
          tar -xvf /tmp/llvm.tar.xz -C /tmp
          mv /tmp/clang+llvm-10.0.0-x86_64-apple-darwin /tmp/LLVM
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
      - name: Build NDCell
        run: cargo build --release
      - name: Download Mac App Shell script
        uses: actions/checkout@v2
        with:
          repository: Xeoncross/macappshell
      - name: Make app
        run:
          sh macappshell/setup.sh NDCell ui/resources/icon/ndcell.svg
          mv target/release/ndcell NDCell.app/Contents/MacOS/NDCell
      - name: Upload app
        uses: actions/upload-artifact@v2
        with:
          name: ndcell_v${{ env.NDCELL_VERSION }}_macos
          path: NDCell.app
